package db.migration;

import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ExpandNotificationEnumConstraintsMigrationTest {

    @Test
    void 기존_enum_제약에_PR_알림_값을_추가한다() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:notification_migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "")) {
            createLegacyNotificationTable(connection);

            assertThrows(SQLException.class, () -> insertPrConsistencyNotification(connection));

            V20260731_01__Expand_notification_enum_constraints.migrate(connection);

            assertDoesNotThrow(() -> insertPrConsistencyNotification(connection));
        }
    }

    @Test
    void notification_테이블이_아직_없어도_신규_DB_부팅을_막지_않는다() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:empty_notification_migration;MODE=PostgreSQL", "sa", "")) {
            assertDoesNotThrow(() -> V20260731_01__Expand_notification_enum_constraints.migrate(connection));
        }
    }

    private void createLegacyNotificationTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE notification (
                        notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        member_id BIGINT NOT NULL,
                        type VARCHAR(30) NOT NULL,
                        title VARCHAR(300) NOT NULL,
                        content TEXT,
                        reference_type VARCHAR(20),
                        reference_id BIGINT,
                        is_read BOOLEAN NOT NULL,
                        created_at TIMESTAMP,
                        CONSTRAINT notification_type_check
                            CHECK (type IN ('PIPELINE_COMPLETE', 'PIPELINE_FAILED', 'TEAM_INVITE', 'MENTION')),
                        CONSTRAINT notification_reference_type_check
                            CHECK (reference_type IN ('PIPELINE', 'PROJECT', 'TEAM'))
                    )
                    """);
        }
    }

    private void insertPrConsistencyNotification(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    INSERT INTO notification (
                        member_id, type, title, content, reference_type, reference_id, is_read, created_at
                    ) VALUES (
                        1, 'PR_CONSISTENCY_REVIEW', '정합성 검토 필요', 'test', 'PULL_REQUEST', 2, FALSE, CURRENT_TIMESTAMP
                    )
                    """);
        }
    }
}
